import { useState } from "react";

const API = location.port === "8003" ? "" : "http://localhost:8003";

const CHECKS = [
  ["Static build", "Done", "web-dist is generated by npm.cmd run build"],
  ["Evidence downloads", "Done", "formal report and docs are bundled under /docs"],
  ["Mock audit", "Demo", "SQLite hash-chain endpoint exists, but not regulated audit"],
  ["Backend report export", "Demo", "HTML export endpoint for browser print/PDF"],
  ["Authentication", "Missing", "no real clinician login or role-based access"],
  ["Database cases", "Missing", "no patient/case database for pilot operations"],
  ["Privacy workflow", "Planned", "PDPA/IRB/de-identification docs exist; app workflow is not complete"],
  ["Monitoring", "Minimal", "process-local /api/metrics only"],
];

export default function Deployment() {
  const [status, setStatus] = useState("Backend has not been checked yet.");
  const [payload, setPayload] = useState<Record<string, unknown> | null>(null);

  async function checkBackend(path: string) {
    setStatus(`Requesting ${path}...`);
    try {
      const r = await fetch(API + path);
      const data = await r.json();
      setPayload(data);
      setStatus(`${path} returned HTTP ${r.status}.`);
    } catch {
      setPayload(null);
      setStatus("Backend unavailable. Start FastAPI at localhost:8003 and try again.");
    }
  }

  return (
    <div className="mx-auto max-w-6xl px-6 py-14">
      <div className="flex flex-wrap items-end justify-between gap-4">
        <div>
          <div className="kicker mb-2">Deployment readiness</div>
          <h1 className="font-display text-3xl font-semibold text-ink md:text-4xl">Demo status and pilot readiness</h1>
          <p className="mt-2 max-w-3xl text-sm leading-6 text-mut">
            This page separates competition-demo readiness from the work still required before a hospital pilot.
            Backend checks are optional; the static demonstration remains available without the server.
          </p>
        </div>
        <a href="/docs/WEB_DEPLOY_READY_CHECKLIST.md" className="rounded-full border border-line px-5 py-2.5 text-sm text-mut transition hover:border-teal hover:text-teal">
          Open checklist
        </a>
      </div>

      <section className="mt-8 grid gap-3 md:grid-cols-4">
        {[
          ["/api/health", "Health"],
          ["/api/ready", "Ready"],
          ["/api/metrics", "Metrics"],
          ["/api/audit", "Audit"],
        ].map(([path, label]) => (
          <button
            key={path}
            onClick={() => checkBackend(path)}
            className="card card-hover p-4 text-left"
            type="button"
          >
            <div className="font-mono text-xs uppercase tracking-[.18em] text-teal">{label}</div>
            <div className="mt-2 text-sm text-mut">{path}</div>
          </button>
        ))}
      </section>

      <section className="mt-5 rounded-2xl border border-line bg-surface p-5">
        <div className="font-display text-lg font-semibold text-ink">Backend response</div>
        <p className="mt-1 text-sm text-mut">{status}</p>
        <pre className="mt-3 max-h-80 overflow-auto rounded-xl bg-paper p-4 font-mono text-xs leading-5 text-ink">
          {payload ? JSON.stringify(payload, null, 2) : "No backend payload yet."}
        </pre>
      </section>

      <section className="mt-10">
        <h2 className="font-display text-2xl font-semibold text-ink">Readiness matrix</h2>
        <div className="mt-4 overflow-hidden rounded-2xl border border-line bg-surface">
          <table className="w-full text-left text-sm">
            <thead className="border-b border-line text-xs uppercase tracking-[.16em] text-mut">
              <tr>
                <th className="px-4 py-3">Area</th>
                <th className="px-4 py-3">Status</th>
                <th className="px-4 py-3">Note</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-line">
              {CHECKS.map(([area, state, note]) => (
                <tr key={area}>
                  <td className="px-4 py-3 font-semibold text-ink">{area}</td>
                  <td className="px-4 py-3">
                    <span className={"rounded-full border px-2 py-1 text-xs " + (state === "Missing" ? "border-scc text-scc" : "border-teal text-teal")}>
                      {state}
                    </span>
                  </td>
                  <td className="px-4 py-3 text-mut">{note}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      <section className="mt-8 rounded-2xl border border-dashed border-line p-5">
        <h2 className="font-display text-xl font-semibold text-ink">Production boundary</h2>
        <p className="mt-2 text-sm leading-6 text-mut">
          This website is ready as a competition demo and evidence package, but it is not hospital-pilot software.
          Work required before real patient data includes authentication, a case database, de-identification, IRB/PDPA workflows,
          a properly designed immutable server-side audit, monitoring, and clinical validation.
        </p>
      </section>
    </div>
  );
}
